config/routes.rb
Rails.application.routes.draw do
  resources :movies
  resources :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "clients#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :client
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Cliente ha sido creado Exitosamente." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Cliente ha sido editado Exitosamente." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client ha sido eliminado Exitosamente." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :age, :direction)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]

  # GET /movies or /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Película ha sido Guardada." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    if movie_params['client_id'] == '1'
      respond_to do |format|
        if @movie.update(movie_params)
          format.html { redirect_to movie_url(@movie), notice: "Película ha sido devuelta" }
          format.json { render :show, status: :ok, location: @movie }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @movie.errors, status: :unprocessable_entity }
        end
      end
    else 
      cliente = Client.find(movie_params['client_id'])
      if cliente.movies.count > 0
        respond_to do |format|
            format.html { redirect_to movie_path, notice: "#{cliente.name}, lo sentimos, no puedes arrendar una nueva película. Ya tienes un arriendo."}
        end
      else
        respond_to do |format|
          if @movie.update(movie_params)
            format.html { redirect_to movie_url(@movie), notice: "La Pelicula ha sido arredada por #{cliente.name}" }
            format.json { render :show, status: :ok, location: @movie }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @movie.errors, status: :unprocessable_entity }
          end
        end
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Película ha sido Eliminada." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:name, :client_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id(client) %>" class="card text-bg-dark">
  <div class="card-body">
    <h5 class="card-title">N° Cliente <%= client.id %></h5>

    <p class="card-text">
      <strong>Nombre Cliente:</strong>
      <%= client.name %>
    </p>

    <p class="card-text">
      <strong>Edad:</strong>
      <%= client.age %>
    </p>

    <p class="card-text">
      <strong>Dirección:</strong>
      <%= client.direction %>
    </p>
  </div>
</div>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">
    <div class="form-group">
      <%= form.label :name, 'Nombre Cliente',  style: "display: block" %>
      <%= form.text_field :name, class: "form-control"%>
    </div>

    <div class="form-group">
      <%= form.label :age, 'Edad', style: "display: block" %>
      <%= form.text_field :age, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :direction, 'Dirección', style: "display: block" %>
      <%= form.text_field :direction, class: "form-control" %>
    </div>

    <div>
      <%= form.submit 'Guardar Cliente', class:"btn btn-success mt-3" %>
    </div>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editar Cliente</h1>

<%= render "form", client: @client %>

<div>
  <%= link_to "Mostrar Cliente", @client, class:"btn btn-info" %> 
  <%= link_to "Volver a Clientes", clients_path, class:"btn btn-primary"%>
</div>

app/views/clients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Clientes</h1>

<table class="table table-dark table-hover table-bordered border-warning">
  <thead>
    <tr>
      <th>Id</th>
      <th>Nombre</th>
      <th>Edad</th>
      <th>Dirección</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.id %></td>
        <td><%= client.name %></td>
        <td><%= client.age %></td>
        <td><%= client.direction %></td>
        <td>
          <%= link_to "Mostrar Cliente", client, class: "btn btn-info" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Nuevo Cliente", new_client_path, class: "btn btn-success mb-3" %>

app/views/clients/new.html.erb
<h1>Nuevo Cliente</h1>

<%= render "form", client: @client %>

<br>
<div>
  <%= link_to "Volver a Clientes", clients_path, class:"btn btn-primary mb-4 m-2" %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<h1>Información Cliente</h1>
<%= render @client %>

<div>
  <div class="container">
    <div class="row">
      <div class="col-10">
        <%= link_to "Editar Cliente", edit_client_path(@client), class:"btn btn-success mt-2"%>
        <%= link_to "Volver a Clientes", clients_path, class:"btn btn-primary mt-2" %>
      </div>
    </div>
  </div>
  
  <div class="container">
    <%= button_to "Eliminar Cliente",@client, method: :delete, class:"btn btn-danger mt-2 mb-5"%>  
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blockbuster Clone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg bg-warning">
      <div class="container-fluid">
        <%= link_to image_tag('blockbuster_logo.png', alt: 'Logo', style: 'width: 100px; height: 70px;'), movies_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <%= link_to 'Películas', movies_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Clientes', clients_path, class: 'nav-link'%>
            </li>
        </div>
      </div>
    </nav>

  <div class="container">
    <%= yield %>
  </div> 

  <footer class="container-fluid bg-warning">
    <div class="row">
      <div class="col-12 text-center">
        <%= link_to image_tag('blockbuster_logo.png', alt: 'Logo', style: 'width: 150px; height: 100px;')%>
      </div>
    </div>

    <div class="row">
      <div class="col-12 text-center">
        <i class="fab fa-facebook fa-2x" style="color: #0b3b8e;"></i>
        <i class="fab fa-instagram fa-2x" style="color: #0b3b8e;"></i>
        <i class="fab fa-github fa-2x" style="color: #0b3b8e;"></i>
      </div>
    </div>
    <div class="row">
      <div class="col-12 text-center mt-3">
        <h6>App construida con conocimientos de Rubi On Rails by CMJ</h6>
      </div>
    </div>

  </footer>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="form-group" >
      <%= form.label :name, 'Nombre Película', style: "display: block" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
  
    <div class="form-group">
      <%= form.label :client_id, 'ID Cliente', style: "display: block" %>
      <%= form.text_field :client_id, class: "form-control" %>
    </div>
  
    <div>
      <%= form.submit 'Guardar Película', class:"btn btn-success mt-3" %>
    </div>
  
  </div>
  <% end %>

app/views/movies/_movie.html.erb
<div id="<<%= dom_id movie %>" class="card text-bg-dark">
  <div class="card-body">
    <h5 class="card-title">Película N°<%= movie.id %></h5>

    <p class="card-text">
      <strong>Nombre Pelicula: </strong>
      <%= movie.name %>
    </p>

    <p class="card-text">
      <strong>Cliente: </strong>
      <%= movie.client.name %>
    </p>
  </div>
</div>

app/views/movies/edit.html.erb
<h1>Editar Peliculas</h1>

<%= render "form", movie: @movie %>

<div>
  <%= link_to "Mostrar Película", @movie, class:"btn btn-danger m-2"%>
  <br>
  <%= link_to "Volver a Películas", movies_path, class:"btn btn-primary m-2" %>
</div>

app/views/movies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Películas</h1>

<table class="table table-dark table-hover table-bordered border-warning">
  <thead>
    <tr>
      <th>Id</th>
      <th>Nombre Película</th>
      <th>Cliente</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.id %></td>
        <td><%= movie.name %></td>
        <td><%= movie.client.name %></td>
        <td>
          <%= link_to "Mostrar Película", movie, class:"btn btn-info" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Nueva Película", new_movie_path, class:"btn btn-success mb-3"%>

app/views/movies/new.html.erb
<h1>Nueva Película</h1>

<%= render "form", movie: @movie %>

<div>
  <%= link_to "Volver a Películas", movies_path, class:"btn btn-primary mb-5 m-2" %>
</div>

app/views/movies/show.html.erb
<p style="color: green"><%= notice %></p>

<h1>Información Películas</h1>

<%= render @movie %>

<div>
  <div class="container">
    <div class="row">
      <div class="col-10">
        <%= link_to "Editar Película", edit_movie_path(@movie), class:"btn btn-success mt-2"%> |
        <%= link_to "Volver a Películas", movies_path, class:"btn btn-primary mt-2" %>
      </div>
    </div>
  </div>

  <div class="container">
    <%= button_to "Eliminar Película", @movie, method: :delete, class:"btn btn-danger mt-2 mb-5"%>  
  </div>
</div>